Ursula: add markers for elastic
freesewing/freesewing pull request #2297
Opened 2022-06-23 20:40 UTC by anna-puk

After calculating the elastic length, markers (notches) are added along the edges of the pattern pieces to indicate how to distribute the elastic. This requires a second set of parts, into which the originals are injected.

2022-06-24 20:58 UTC, nataliasayang commented
@joostdecock Thanks for tagging me. I don't have the capacity to review this in depth right now, but conceptually I'm fine with it. It seems to replace part of [Step 8 in the Ursula instructions](https://freesewing.org/docs/patterns/ursula/instructions/) (divide into quarters) with code. This practice doesn't seem to be typical -- I just looked at several other patterns and they all had some variation of "divide into quarters" and none had notches -- but I can't think of any reason it shouldn't work fine.

The only other impact I can think of is that I will need to edit the instructions. I'll do that at some point.

2022-06-24 20:59 UTC, nataliasayang reviewed
https://github.com/freesewing/freesewing/pull/2297#issuecomment-1165933516

2022-06-24 20:59 UTC, nataliasayang approved these changes
https://github.com/freesewing/freesewing/pull/2297#issuecomment-1165933516

2022-06-27 10:05 UTC, joostdecock requested changes

2022-06-27 18:41 UTC, anna-puk commented on designs/ursula/src/front2.js
> +export default function (part) {
The full length of the elastic is not known until all parts are drawn. This approach was recommended to me as an alternative to postDraft.

2022-06-27 18:41 UTC, anna-puk commented on designs/ursula/src/gusset2.js
> +export default function (part) {
(also here) The full length of the elastic is not known until all parts are drawn.

2022-06-27 19:15 UTC, anna-puk commented on designs/ursula/src/back2.js
> +export default function (part) {
(also here) The full length of the elastic is not known until all parts are drawn.

2022-06-27 20:29 UTC, anna-puk commented on designs/ursula/src/elastic.js
> +  }
This results in seven parts for the else if statement, since the if statements were partially independent. (I did it anyway.)

2022-06-28 07:05 UTC, joostdecock commented on designs/ursula/src/front2.js
> +export default function (part) {
ok, makes sense

2022-06-28 07:21 UTC, joostdecock approved these changes

2022-06-28 07:22 UTC, merged