Allow `defs` in the `svg` to be overwritten.
freesewing/freesewing pull request #3863
Opened 2023-04-20 17:53 UTC by woutervdub

Implements #3819

2023-04-20 18:32 UTC, eriese requested changes
Great work!

My one nitpick is that I think it'd be ideal if all the snippets were treated the way you've done `buttons`, i.e. each individual `snippet` gets added to `defs` via its own `id`, rather than all being grouped by function

2023-04-20 18:40 UTC, woutervdub commented
The buttons one is different because there were multiple `defs` in the original. Each of those `defs` is itself made up from separate `id`s. So the `cutOnFold` is really the same as `snaps`, whereas `cutOnFold` is in its own mjs source file, while `snaps` is combined in the buttons mjs source file.

2023-04-20 18:40 UTC, woutervdub commented
I guess I broke a bunch of tests.

2023-04-20 19:39 UTC, eriese commented on packages/core/tests/svg.test.mjs
> +    expect(svg.defs instanceof Defs).to.equal(true)
there's a handy assertion you can use here that's a little more readable. `expect(svg.defs).to.be.an.instanceof(Defs)`. It'll throw a better error

2023-04-20 19:41 UTC, eriese commented on plugins/plugin-annotations/tests/buttons.test.mjs
> +      expect(pattern.svg.defs.render().indexOf(`<g id="${snippet}">`)).to.not.equal(-1)
change this to `expect(pattern.svg.defs).to.have.property(snippet)`

2023-04-20 19:41 UTC, eriese commented on plugins/plugin-annotations/tests/logo.test.mjs
> +    expect(pattern.svg.defs.render()).to.contain(
same here. `expect(pattern.svg.defs).to.have.property('logo')`

2023-04-20 19:42 UTC, eriese commented on plugins/plugin-annotations/tests/notches.test.mjs
> +    expect(pattern.svg.defs.render().indexOf(`<g id="notch">`)).to.not.equal(-1)
These as well

2023-04-21 06:26 UTC, eriese submitted a review, later dismissed

2023-04-21 06:28 UTC, eriese commented
It's looking really good. Only thing is test coverage. I'd say if you haven't seen a use case for `Defs.prototype.clone()` you could get rid of it and save yourself a test

2023-04-21 14:08 UTC, eriese approved these changes

2023-04-26 19:51 UTC, BenJamesBen commented
I do not know if these are related to this PR's changes or if they simply might be due to this PR being based on older code, but I notice that in Cutting Layout:
1. Parts no longer align with grain when the grainline is toggled to horizontal.
2. Cutonfold parts are no longer mirrored/splayed.
3. Some parts no longer show via `complete`, like Carlita's `carlton.back`.

2023-04-26 21:19 UTC, eriese commented
I think that's because this branch is 230 commits behind `develop`, and those things were broken in the move to `plugin-annotations`, but I think it's probably best for @woutervdub to merge in develop to find out

2023-05-02 17:36 UTC, eriese commented
@joostdecock I'm good with this, but don't want to merge it without your approval because I think you had a point of view about how this should be implemented

2023-05-02 18:03 UTC, merged

2023-05-02 18:06 UTC, joostdecock commented
I had a small remark but it's not something @woutervdub did, just something I noticed while reviewing this.
So I've merged this (great work) and created: #3965 3965