adds the "dona" design, which extends simone into a shirt dress
freesewing/freesewing pull request #3876
Opened 2023-04-24 03:38 UTC by Mesil

Author:    Mesil <14284175+Mesil@users.noreply.github.com>

Actual changes to the design are contained in between the "being changes to modify into a dress pattern" and "end changes to modify into a dress pattern" lines in fba-front.mjs and back.mjs.

I'm sure there's a much more elegant way to do pretty much all of this, but this at least works :)

To do:
- add options for additional collar styles (camp)
- add options for additional sleeve styles (cap, 1/2, 3/4, etc
- add additional options of skirt silhouette
- - the hem style options have an interesting effect, it would be nice to refine them for this use case
- - additional control points for adjusting fullness of the skirt would be helpful
- add a lower bound on skirt length (never less than waistToFloor - inseam?)
- fix button / button hole distribution
- fix placement of front darts

2023-04-25 04:21 UTC, BenJamesBen commented
FYI, I had to change `config/software/designs.json` and run `yarn kickstart` to get the design to show up in the lab.

```diff
@@ -193,6 +193,13 @@
       "difficulty": 2,
       "tags": ["tops"]
     },
+    "dona": {
+      "description": "A FreeSewing pattern for a shirt dress",
+      "code": "Mesil",
+      "design": "Mesil",
+      "difficulty": 2,
+      "tags": ["tops"]
+    },
     "huey": {
       "description": "A FreeSewing pattern for a zip-up hoodie",
       "code": "Joost De Cock",
```

A similar change to that file will need to be added to this PR.

2023-04-25 06:16 UTC, BenJamesBen commented
I tested the PR in the lab, and it seems to generate patterns just fine. The code and implementation has issues, but other than the missing required `config/software/designs.json` change, I believe that the PR could be merged for wider testing.

2023-04-25 06:17 UTC, BenJamesBen requested changes

2023-04-29 17:36 UTC, Mesil commented on designs/dona/src/index.mjs
> +} from '@freesewing/simon'
updated to adopt suggesting :)

2023-04-29 17:37 UTC, Mesil commented on designs/dona/src/index.mjs
> +  Dona
updated, all parts now exported

2023-04-29 17:38 UTC, Mesil commented on designs/dona/src/fba-front.mjs
> +import { lengthBonus } from './options.mjs'
updated, import removed

2023-05-03 03:48 UTC, BenJamesBen commented
Your Dona repository seems to be 7-months old. You might want to save a copy of your repository, update the repository to the latest `develop`, and then continue testing and working on  Dona using the latest `develop`. 

`git pull` will update `develop`, but there might be conflicts to resolve with `config/software/designs.json` which I know has been updated since. (That is why I advised saving a copy of the repository first, in case you might need or want to start over from scratch with a fresh clone of the repository.)

Otherwise, I tested Dona both in your repository and the latest `develop`, and the design seems to work without issues.

2023-05-03 03:57 UTC, BenJamesBen approved these changes
I retested the updated PR, and I still believe that the PR could be merged for wider testing.

We will want to consider implementing a designation or category for provisional or still-being-tested designs, since Dona's code still needs some work. And, there is no documentation yet for the design.

2023-05-03 03:57 UTC, BenJamesBen commented on designs/dona/src/index.mjs
> +} from '@freesewing/simon'
It looks like you might still be importing from Simon.

2023-05-03 03:57 UTC, BenJamesBen commented on designs/dona/src/back.mjs
> +function simonBack({
This function is still named `simonBack()`, rather than something like 'donaBack()`.

2023-05-03 03:57 UTC, BenJamesBen commented on designs/dona/src/back.mjs
> +  paths.newhem = new Path().move(points.cbHem).line(points.hemCalc)
The log messages are no longer seen in your copy of the repository. However, your repository is 7 months old. When I copied the dona files over to the latest `develop` branch, I still saw the log messages.
```
0 | points.hemCalc was set with a x parameter that is not a number
1 | points.hemCalc was set with a y parameter that is not a number
2 | points.hemCalc was set with a x parameter that is not a number
...
```

2023-10-30 14:49 UTC, joostdecock commented
Hi @Mesil sorry for the long delay, we've been busy with version 3, but we are slowly starting to see the end of our todo list.

This will probably need a few more tweaks, though I am certain we can make this land in the repo.
Do you have time to pull/merge the latest develop branch so that these changes can be rebased to the current state of our repo?

If so, please do. If not, let us know how you'd like to proceed to land this PR.

2023-12-09 14:21 UTC, joostdecock commented
@mesil Friendly reminder :point_down: 

> Hi @Mesil sorry for the long delay, we've been busy with version 3, but we are slowly starting to see the end of our todo list.
> 
> This will probably need a few more tweaks, though I am certain we can make this land in the repo. Do you have time to pull/merge the latest develop branch so that these changes can be rebased to the current state of our repo?
> 
> If so, please do. If not, let us know how you'd like to proceed to land this PR.

2024-02-10 13:26 UTC, joostdecock commented
Stale. Closing. @Mesil feel free to revive this when you come around to it.

2024-02-10 13:26 UTC, closed without merging