fix(bob,penelope,docs): Access optional measurements via `measurements`
freesewing/freesewing pull request #3974
Opened 2023-05-04 01:52 UTC by BenJamesBen

Fixes #3933.

2023-05-04 06:07 UTC, woutervdub commented
I checked the functionality, and all seems right.

2023-05-04 06:10 UTC, woutervdub approved these changes

2023-05-16 17:42 UTC, SeaZeeZee commented
@joostdecock same as previous, wouter reviewed this so its ready to go!

2023-05-17 00:16 UTC, eriese requested changes

2023-05-17 00:16 UTC, eriese commented on markdown/dev/reference/api/part/config/measurements/en.md
> +</Tip>
Sorry to nitpick, but I don't think this goes here. It's not relevant to a user who has come to the docs to figure out how to specify which measurements are required by a part, and I worry it's confusing to see in this context

I think it should move to `markdown/dev/api/part/draft/en.md`, where it is relevant to a user who is looking at how to access measurements in the draft method and there is currently no note

2023-05-18 06:49 UTC, merged