Add documentation for three macros
freesewing/freesewing pull request #4004
Opened 2023-05-06 16:55 UTC by woutervdub

crossbox, pleat, and sewTogether

2023-05-07 12:04 UTC, SeaZeeZee approved these changes
This looks great to me!

2023-05-07 19:45 UTC, BenJamesBen requested changes
You'll probably want to fix all the typos and small corrections anyway, but the only change I actually am requesting is to correct the instances of "sewtogether" to "sewTogether". The capitalization difference actually caused an issue during my testing, where it took me a while to figure out why the "sewtogether" macro wasn't working for me.

2023-05-07 19:45 UTC, BenJamesBen commented on markdown/dev/reference/macros/pleat/en.md
> +| `from`          |          | [Point](/reference/api/point) | The top left point of the crossbox |
```suggestion
| `from`          |          | [Point](/reference/api/point) | The start point of the pleat |
```

2023-05-07 19:45 UTC, BenJamesBen commented on markdown/dev/reference/macros/pleat/en.md
> +| `to`            |          | [Point](/reference/api/point) | The bottom right point of the crossbox |
```suggestion
| `to`            |          | [Point](/reference/api/point) | The end point of the pleat |
```

2023-05-07 19:45 UTC, BenJamesBen commented on markdown/dev/reference/macros/sewtogether/en.md
> +title: sewtogether
```suggestion
title: sewTogether
```

2023-05-07 19:45 UTC, BenJamesBen commented on markdown/dev/reference/macros/sewtogether/en.md
> +The `sewtogether` macro is used to mark where two parts of the same `part` need
```suggestion
The `sewTogether` macro is used to mark where two parts of the same `part` need 
```

2023-05-07 19:45 UTC, BenJamesBen commented on markdown/dev/reference/macros/sewtogether/en.md
> +| `prefix`        | 'pleat'  | String   | The prefix to be used for creating all the points and paths |
```suggestion
| `prefix`        | 'sewtogether'  | String   | The prefix to be used for creating all the points and paths |
```

2023-05-07 20:13 UTC, woutervdub commented on markdown/dev/reference/macros/crossbox/en.md
> +| `points.${id}_textAnchor` | Point for the text |
This has been fixed this morning.

2023-05-07 20:15 UTC, woutervdub commented on markdown/dev/reference/macros/crossbox/en.md
> +| `points.${id}_textAnchor` | Point for the text |
(in PR #3999)

2023-05-07 20:29 UTC, BenJamesBen approved these changes

2023-05-16 18:05 UTC, SeaZeeZee commented
@joostdecock This can also be merged!

2023-05-18 06:39 UTC, merged