Onyx One-piece
freesewing/freesewing pull request #5234
Opened 2023-10-21 18:01 UTC by Thrunic

Onyx is ready for review. It's feature complete, I've written the documentation, and I think it's ready to be tested.

2023-10-22 11:55 UTC, joostdecock commented
Can you address the eslint errors @Thrunic ?

2023-10-22 14:20 UTC, Thrunic commented
> Can you address the eslint errors @Thrunic ?

This one works now: ESLint Changed Files / lint (18.x) (pull_request) Successful in 1m

ESLint All Files / lint (18.x) still fails on files that are not part of Onyx.

2023-10-23 18:00 UTC, joostdecock requested changes
This is great stuff @Thrunic 
There's a lot of repeating things that I pointed out, so all in all it's just a couple of issues.
However, people tend to copy/paste from other designs, so it's important to do things the best way so that others don't copy bad habits.

2023-10-23 22:16 UTC, Thrunic commented on designs/onyx/src/back.mjs
> +          .attr('class', 'fabric sa')
Is there a difference between 'sa fabric' and 'fabric sa'?

2023-10-23 22:58 UTC, Thrunic commented on designs/onyx/src/raglansleeve.mjs
> +  measurements: ['neck', 'chest', 'biceps', 'wrist', 'shoulderToWrist'],
'shoulderToWrist', 'biceps', and 'wrist' aren't declared elsewhere.

2023-10-23 23:01 UTC, Thrunic commented on designs/onyx/src/hood.mjs
> +  measurements: ['neck', 'chest', 'biceps', 'wrist', 'head'],
'head' isn't declared elsewhere.

2023-10-23 23:28 UTC, Thrunic commented on designs/onyx/src/zipperguard.mjs
> +  after: [front, neckband],
Everything it needs is actually just in base, so I changed it to after: [base], and changed the imports on top.

2023-10-23 23:29 UTC, Thrunic commented on designs/onyx/src/zipperguard.mjs
> +  after: [front, neckband],
Everything it needs is actually just in base, so I changed it to after: [base], and changed the imports on top.

2023-10-23 23:30 UTC, Thrunic commented on designs/onyx/src/zipperguard.mjs
> +import { front } from './front.mjs'
Both imports replaced by base from ./base.mjs

2023-10-24 00:02 UTC, Thrunic commented
@joostdecock I've fixed the issues noted in your comments. There's a few that I'm not sure about, so I put replies in those messages and left them unresolved.

I'm also pretty sure there's going to be a bunch unneeded lines of code, mostly in the function draftPartName declarations. I'm going to run tests and get rid of them.

Lastly, I noticed that I neglected to make a zipperPosition option (list option, possible values of front (default), back, none). I'm going to add that in, and make the needed changes of the code to draw the zipper on the correct piece.

I'll post another message when the code is ready for further review.

2023-10-24 01:55 UTC, Thrunic commented
@joostdecock Onyx should be ready for further review. I've made all requested changes, along a few other small fixes/additions.

There were several changes that I felt were missing something. I've left a comment on those conversations and fixed them with what I believe is correct. If there are still errors, please let me know.

Thank you again for all your hard work.

2023-10-24 10:02 UTC, joostdecock approved these changes

2023-10-24 10:03 UTC, merged