Add disabled pattern delete button when no patterns selected
freesewing/freesewing pull request #5731
Opened 2023-12-30 23:15 UTC by ArcticCoder

Adds a grey/disabled delete button to `account/patterns` when no patterns are selected. Motivated by multiple users (me included) at least initially glossing over the fact that this is how pattern deletion is done.

2024-01-01 07:52 UTC, joostdecock reviewed
No need to duplicate the button markup here. You can use the `disabled` attribute. Something like:

```js
<button
  onClick=...
  className=...
  disabled={selCoumt < 1}
>
...
</bultton>
```

2024-01-01 07:54 UTC, joostdecock requested changes
Keep in mind that disabled should evaluate to `true` to disable the button

2024-01-01 12:03 UTC, ArcticCoder commented
Doih :facepalm: :sweat_smile:  Thanks :D

2024-01-01 13:07 UTC, joostdecock approved these changes

2024-01-01 13:07 UTC, merged

2024-01-01 13:11 UTC, joostdecock commented
Great work again @ArcticCoder thanks a bunch, and happy new year 🎉

2024-01-02 11:45 UTC, joostdecock commented
Just realized that this makes the UI somewhat inconsistent as there's other pages that use the same list of items with the *select one to make the delete button appear* approach:

- https://freesewing.org/account/bookmarks
- https://freesewing.org/account/sets
- https://freesewing.org/account/apikeys

Any chance you'd like to update those too @ArcticCoder ?

2024-01-02 12:21 UTC, ArcticCoder commented
> Just realized that this makes the UI somewhat inconsistent as there's other pages that use the same list of items with the _select one to make the delete button appear_ approach:
> 
>     * https://freesewing.org/account/bookmarks
> 
>     * https://freesewing.org/account/sets
> 
>     * https://freesewing.org/account/apikeys
> 
> 
> Any chance you'd like to update those too @ArcticCoder ?

Sure thing! ☺️