fix(markdown): Fix typos in designs documentation
freesewing/freesewing pull request #5876
Opened 2024-01-23 03:39 UTC by BenJamesBen

I went through all the designs documentation with a spellchecker and fixed all the typos I found.

- I tried to skip terms that were ambiguous about their spelling correctness, like sewing terminology and other words that might not have an agreed-upon correct spelling.
- I tried to skip grammar, punctuation, and whitespace issues.

If I made any mistakes or changed words that were actually correct or were spelling variants, please let me know and I'll change them back.

For all the affected designs, I will add the pattern designer as requested reviewers for this PR.

2024-01-23 07:24 UTC, bobgeorgethe3rd requested changes

2024-01-23 07:24 UTC, bobgeorgethe3rd commented on markdown/org/docs/designs/bee/instructions/en.md
> +You may prefer to wrap the one cup over the other at the midpoint. To do this place the sides of the cups at the other notches and lay their fronts pass the midpoint with the left on top.
```suggestion
You may prefer to wrap the one cup over the other at the midpoint. To do this place the sides of the cups at the outer notches and lay their fronts pass the midpoint with the left on top.
```

2024-01-23 07:24 UTC, bobgeorgethe3rd commented on markdown/org/docs/designs/hi/options/hungry/en.md
> +This setting determine how long it has been since your Hi has had
```suggestion
This setting determines how long it has been since your Hi has had
```

2024-01-23 14:37 UTC, bobgeorgethe3rd commented on markdown/org/docs/designs/charlie/options/beltloops/en.md
> +Control how many beltloops we'll generate.
```suggestion
Controls how many beltloops we'll generate.
```

2024-01-23 14:44 UTC, bobgeorgethe3rd commented on markdown/org/docs/designs/simone/options/seperatebuttonplacket/en.md
>  title: "Seperate button placket"
```suggestion
title: "Separate button placket"
```

2024-01-23 14:44 UTC, bobgeorgethe3rd commented on markdown/org/docs/designs/simone/options/seperatebuttonholeplacket/en.md
>  title: "Seperate buttonhole placket"
```suggestion
title: "Separate buttonhole placket"
```

2024-01-24 07:27 UTC, joostdecock approved these changes
You know what, I was wrong.
Turns out we do have a documentation team. It's one guy named Ben 😉

2024-01-24 07:27 UTC, merged