fix(markdown): Path doc updates for optional parameters
freesewing/freesewing pull request #5990
Opened 2024-02-08 16:06 UTC by BenJamesBen

2024-02-10 13:15 UTC, joostdecock requested changes

2024-02-10 13:15 UTC, joostdecock commented on markdown/dev/reference/api/path/addtext/en.md
> +Path path.addText(string text[, string className])
While that `[ brackets ]` notation is rather common in man files and so on, it's not how we tend to document things in the FreeSewing docs.

Parameters that are optional typically have a default value. So I'm in favor of showing that:
```mjs
Path path.addText(string text, string className = '')
```

This makes it obvious the parameter is optional to people who are used to JavaScript, as opposed to people who are used to read man pages.

2024-02-10 13:15 UTC, joostdecock commented on markdown/dev/reference/api/path/attr/en.md
> +  mixed value[,
Same remark. No need for the square brackets as the optional value has a default assigned.

2024-02-10 13:15 UTC, joostdecock commented on markdown/dev/reference/api/path/join/en.md
> +Path path.join(path other[, bool closed=false])
Same remark. No need for the square brackets as the optional value has a default assigned.

2024-02-10 13:15 UTC, joostdecock commented on markdown/dev/reference/api/path/settext/en.md
> +Path path.setText(string text[, string className])
Same remark. No need for the square brackets as the optional value has a default assigned.

2024-02-11 14:40 UTC, BenJamesBen commented
Changed the optional parameters from man page format to JavaScript format, in all files.

2024-02-11 16:37 UTC, joostdecock approved these changes

2024-02-11 16:37 UTC, merged