Implements #6457
freesewing/freesewing pull request #6480
Opened 2024-03-30 17:22 UTC by woutervdub

2024-04-01 21:21 UTC, woutervdub commented on designs/noble/src/frontpoints.mjs
> +    points.bust
Ah, you're right. For visualization I did a `addCircle(3)` here. Thewn before committing, I removed all of those `.addCircle()`parts. But I forgot to go over these artifacts of the regEx.

2024-04-01 22:15 UTC, woutervdub commented
Oops, added another fix into this PR.

2024-04-03 12:46 UTC, HaasJona commented
Trying to link the fixed issues here:

Fixes #6447
Fixes #6478
Fixes #6457

2024-04-04 17:05 UTC, HaasJona commented on designs/noble/src/frontpoints.mjs
> +const createTopRightDartPoints = (points, Path, paths, options) => {
`paths` is unused here

2024-04-05 06:12 UTC, HaasJona requested changes

2024-04-05 06:12 UTC, HaasJona commented on designs/noble/src/frontpoints.mjs
> +    .join(createTopRightDartPoints(points, Path, paths, options))
You also need to remove the `paths` argument here (and maybe at locations where that method is called), or else it fails to run properly.

2024-04-06 16:01 UTC, joostdecock approved these changes

2024-04-06 16:01 UTC, merged