[feature]: Bibi: Add waistband, cuff and neck finish option
freesewing/freesewing pull request #6776
Opened 2024-05-18 11:39 UTC by HaasJona

Fixes #6775

2024-06-12 13:08 UTC, joostdecock requested changes
Just drop that `console.log()` and we're good to go :)

2024-06-12 13:08 UTC, joostdecock commented on designs/bibi/src/front.mjs
> +    console.log('dart', length, path)
Please remove this debug output

2024-06-12 14:31 UTC, HaasJona commented on designs/bibi/src/front.mjs
> +    console.log('dart', length, path)
Done.

2024-06-13 13:42 UTC, joostdecock approved these changes

2024-06-13 13:43 UTC, merged