Fix clarity issues with the straps #6931
freesewing/freesewing pull request #6932
Opened 2024-07-03 05:52 UTC by woutervdub

2024-07-03 07:39 UTC, HaasJona requested changes

2024-07-03 07:39 UTC, HaasJona commented on markdown/org/docs/designs/waralee/instructions/en.md
> +##### Tradisionally, the straps are the same size
Typo: Tradisionally

2024-07-03 07:39 UTC, HaasJona commented on markdown/org/docs/designs/waralee/options/knotinfront/en.md
> +that to a set tied in the front and in the back, the traditional way.
If the knot in front option is set to "Knot in Back", the back ties are made longer instead, so both straps will be tied in the back. That contradicts this documentation. With knot in the back selected, both ties probably should be the same length or the option should be split into 3 (both ties at the front, both ties at the back, and the traditional way with shorter same-length straps).

2024-07-08 06:39 UTC, HaasJona approved these changes
The markdown documentation for "knotInFront" is now unused and probably can be deleted (unless someone still wants to keep it for compatibility or whatever?) but other than that, looks good to me.

2024-07-31 07:26 UTC, joostdecock requested changes

2024-07-31 07:26 UTC, joostdecock commented on designs/waralee/src/waistband.mjs
> +      waistBandLength += options.knotPlacement == 'front' ? measurements.waist / 2 : 0
`===` instead of `==` please 😊

It's a good habit to use strict comparison to avoid subtle type bugs, even if in this case there's no real risk.

2024-07-31 07:26 UTC, joostdecock commented on designs/waralee/src/waistband.mjs
> +      waistBandLength += options.knotPlacement == 'back' ? measurements.waist / 2 : 0
`===` instead of `==` please 😊

It's a good habit to use strict comparison to avoid subtle type bugs, even if in this case there's no real risk.

2024-08-03 14:10 UTC, joostdecock approved these changes

2024-08-03 14:10 UTC, merged