fix(docs): Changes and additions to measurements FAQ
freesewing/freesewing pull request #7103
Opened 2024-09-18 16:04 UTC by BenJamesBen

Some improvements to the "I'm having trouble with measurements. What should I check?" measurements FAQ https://freesewing.org/docs/about/faq/measurements-issues

With input from the community:
https://discord.com/channels/698854858052075530/1101975649419268186/1285298538078666905
discord://discord.com/channels/698854858052075530/1101975649419268186/1285298538078666905

(These are just my suggested improvements. People should feel free to subsequently change or add anything as needed.)

2024-09-21 14:16 UTC, RockerKitten commented on markdown/org/docs/about/faq/measurements-issues/en.md
Suggest changing line 120 https://github.com/freesewing/freesewing/pull/7103/commits/447107848eb15985ba868b2f1e8c119c676fcd43#:~:text=the%20elastic%20band%20at%20the%20location%20of%20your%20natural%20waist.
to `the elastic band at the location you think most accurately denotes your natural waist`

2024-09-21 14:17 UTC, RockerKitten requested changes
Suggest changing line 120 https://github.com/freesewing/freesewing/pull/7103/commits/447107848eb15985ba868b2f1e8c119c676fcd43#:~:text=the%20elastic%20band%20at%20the%20location%20of%20your%20natural%20waist.
to `the elastic band at the location you think most accurately denotes your natural waist`

2024-09-22 01:01 UTC, BenJamesBen commented
> Suggest changing line 120 [4471078#:~:text=the%20elastic%20band%20at%20the%20location%20of%20your%20natural%20waist](https://github.com/freesewing/freesewing/commit/447107848eb15985ba868b2f1e8c119c676fcd43#:~:text=the%20elastic%20band%20at%20the%20location%20of%20your%20natural%20waist). to `the elastic band at the location you think most accurately denotes your natural waist`

Thanks @RockerKitten. I made the suggested change.

2024-09-28 12:58 UTC, joostdecock approved these changes

2024-09-28 12:58 UTC, merged